# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: true
latex: false
r_packages:
  - covr
warnings_are_errors: true
before_install:
  -  sudo apt-get install libgsl0-dev
r_check_args: '--ignore-vignettes --no-examples'
after_success:
  - Rscript -e 'library(covr); codecov()'
